CREATE TABLE blogs
(
    id SERIAL PRIMARY KEY ,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL ,
    author_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE ,
    created_at TIMESTAMP DEFAULT NOW()
)

ALTER TABLE blogs RENAME COLUMN description TO content;

ALTER TABLE blogs ADD COLUMN updated_at TIMESTAMP DEFAULT NOW();


ALTER TABLE blogs ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
